# -*- generated by 1.0.12 -*-
import da
PatternExpr_686 = da.pat.TuplePattern([da.pat.ConstantPattern('CAPTURE'), da.pat.FreePattern('ph'), da.pat.FreePattern('l'), da.pat.FreePattern('node')])
PatternExpr_697 = da.pat.FreePattern('sender')
PatternExpr_854 = da.pat.TuplePattern([da.pat.ConstantPattern('ACCEPT'), da.pat.FreePattern('ph'), da.pat.FreePattern('l')])
PatternExpr_863 = da.pat.FreePattern('sender')
PatternExpr_933 = da.pat.TuplePattern([da.pat.ConstantPattern('ACK'), da.pat.FreePattern('node')])
PatternExpr_940 = da.pat.FreePattern('sender')
PatternExpr_970 = da.pat.TuplePattern([da.pat.ConstantPattern('ELECTED'), da.pat.FreePattern('node')])
PatternExpr_977 = da.pat.FreePattern('sender')
PatternExpr_1008 = da.pat.TuplePattern([da.pat.ConstantPattern('INFORM'), da.pat.FreePattern('x')])
PatternExpr_1015 = da.pat.FreePattern('sender')
PatternExpr_1053 = da.pat.TuplePattern([da.pat.ConstantPattern('OWNER'), da.pat.FreePattern('node')])
PatternExpr_1060 = da.pat.FreePattern('sender')
_config_object = {}
import sys
import math
import random
import time

class P(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_0', PatternExpr_686, sources=[PatternExpr_697], destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_685]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_1', PatternExpr_854, sources=[PatternExpr_863], destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_853]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_2', PatternExpr_933, sources=[PatternExpr_940], destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_932]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_3', PatternExpr_970, sources=[PatternExpr_977], destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_969]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_4', PatternExpr_1008, sources=[PatternExpr_1015], destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_1007]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_5', PatternExpr_1053, sources=[PatternExpr_1060], destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_1052])])

    def setup(self, hCycle, **rest_1215):
        super().setup(hCycle=hCycle, **rest_1215)
        self._state.hCycle = hCycle
        self._state.n = len(self._state.hCycle)
        self._state.m = int((2 ** math.floor(math.log(self._state.n, 2))))
        self._state.k = (self._state.m / (2 ** math.ceil(math.log(math.log(self._state.m, 2), 2))))
        self._state.state = 'candidate'
        self._state.level = 0
        self._state.phase = 1
        self._state.owner = 0
        self._state.ring = [self._state.hCycle[int(((i * self._state.k) % self._state.n))] for i in range(int(math.ceil((self._state.n / self._state.k))))]
        self._state.ringPh2 = []
        self._state.step = 0
        self._state.Received = False
        self._state.Response = 0
        self._state.done = False
        self._state.first_msg = True
        self._state.leaderid = None
        self._state.receiving_flag = False
        self._state.decided = 0
        self._state.wake_rate = 0.8
        self._state.awaken = random.random()
        self._state.waitState = 0
        self._state.waitTime = 0
        if (not (self._state.m == self._state.n)):
            for i in range(1, int(math.ceil((self._state.n / self._state.k)))):
                index = (- int(((i * self._state.k) % self._state.n)))
                if (not (self._state.hCycle[index] in self._state.ring)):
                    self._state.ring.append(self._state.hCycle[index])

    def run(self):
        if (self._state.awaken > self._state.wake_rate):
            (self._state.state == 'captured')
        if (self._state.state == 'candidate'):
            self.candidateAct()
        if ((self._state.state == 'captured') and (self._state.leaderid == None)):
            self.capturedAct()
        self.output(time.clock())

    def candidateAct(self):
        while ((self._state.state == 'candidate') and (self._state.phase == 1)):
            if (self._state.level >= len(self._state.ring)):
                self.send(('OWNER', self._id), to=self._state.ring)
                self._state.Response = 0
            else:
                self.send(('CAPTURE', 1, self._state.level, self._id), to=self._state.ring[int(((self._state.level + 1) % len(self._state.ring)))])
            self._state.Received = False
            while ((self._state.state == 'candidate') and (self._state.phase == 1) and (self._state.Received == False)):
                self._state.waitState = 1
                super()._label('_st_label_459', block=False)
                _st_label_459 = 0
                while (_st_label_459 == 0):
                    _st_label_459 += 1
                    if self._state.receiving_flag:
                        _st_label_459 += 1
                    else:
                        super()._label('_st_label_459', block=True)
                        _st_label_459 -= 1
                else:
                    if (_st_label_459 != 2):
                        continue
                if (_st_label_459 != 2):
                    break
                self._state.receiving_flag = False
        if ((self._state.state == 'candidate') and (self._state.phase == 2)):
            self._state.step = 1
            while (self._state.state == 'candidate'):
                self._state.ringPh2 = []
                for i in range(1, int(((2 ** (self._state.step - 1)) + 1))):
                    index = int((((i * self._state.k) / (2 ** self._state.step)) % self._state.n))
                    if (not (self._state.hCycle[index] in self._state.ring)):
                        self._state.ringPh2.append(self._state.hCycle[index])
                if (not (self._state.n == self._state.m)):
                    for i in range(1, int(((2 ** (self._state.step - 1)) + 1))):
                        index = (- int((((i * self._state.k) / (2 ** self._state.step)) % self._state.n)))
                        if (not (self._state.hCycle[index] in (self._state.ring + self._state.ringPh2))):
                            self._state.ringPh2.append(self._state.hCycle[index])
                self.send(('CAPTURE', 2, self._state.step, self._id), to=self._state.ringPh2)
                self._state.Received = False
                self._state.Response = 0
                while ((self._state.state == 'candidate') and (self._state.Received == False)):
                    if (len(self._state.ringPh2) == 0):
                        self._state.step = (self._state.step + 1)
                        if (self._state.step >= (math.log(self._state.k, 2) + 1)):
                            self._state.state = 'leader'
                        break
                    self._state.waitState = 2
                    super()._label('_st_label_628', block=False)
                    _st_label_628 = 0
                    while (_st_label_628 == 0):
                        _st_label_628 += 1
                        if self._state.receiving_flag:
                            _st_label_628 += 1
                        else:
                            super()._label('_st_label_628', block=True)
                            _st_label_628 -= 1
                    else:
                        if (_st_label_628 != 2):
                            continue
                    if (_st_label_628 != 2):
                        break
                    self._state.receiving_flag = False
            if (self._state.state == 'leader'):
                self.send(('ELECTED', self._id), to=self._state.hCycle)
                self._state.leaderid = self._id

    def capturedAct(self):
        self._state.done = False
        self._state.first_msg = True
        while (self._state.done == False):
            if (self._state.first_msg == True):
                self._state.state = 'captured'
                self._state.owner = 0
                self._state.phase = 1
            self._state.waitState = 3
            super()._label('_st_label_675', block=False)
            _st_label_675 = 0
            while (_st_label_675 == 0):
                _st_label_675 += 1
                if self._state.receiving_flag:
                    _st_label_675 += 1
                else:
                    super()._label('_st_label_675', block=True)
                    _st_label_675 -= 1
            else:
                if (_st_label_675 != 2):
                    continue
            if (_st_label_675 != 2):
                break
            self._state.receiving_flag = False
            self._state.first_msg = False

    def stall(self):
        super()._label('_st_label_1110', block=False)
        _st_label_1110 = 0
        self._timer_start()
        while (_st_label_1110 == 0):
            _st_label_1110 += 1
            if False:
                pass
                _st_label_1110 += 1
            elif self._timer_expired:
                pass
                _st_label_1110 += 1
            else:
                super()._label('_st_label_1110', block=True, timeout=self._state.waitTime)
                _st_label_1110 -= 1

    def _P_handler_685(self, ph, l, node, sender):
        self.stall()
        self._state.receiving_flag = True
        if (self._state.waitState == 1):
            if (ph == 1):
                if ((self._state.level < l) or ((self._state.level == l) and (self._id < node))):
                    self.send(('ACCEPT', 1, self._state.level), to=sender)
                    self._state.state = 'captured'
                elif (self._id == node):
                    self.send(('ACCEPT', 1, self._state.level), to=sender)
            elif (ph == 2):
                self._state.state = 'captured'
                self._state.phase = 2
                self.send(('ACCEPT', 2, 0), to=sender)
        elif (self._state.waitState == 2):
            if (ph == 2):
                if ((l > self._state.step) or ((l == self._state.step) and (node > self._id))):
                    self.send(('ACCEPT', 2, 0), to=sender)
                    self._state.state = 'captured'
                elif (self._id == node):
                    self.send(('ACCEPT', 2, 0), to=sender)
        elif (self._state.waitState == 3):
            if (ph == 1):
                if (self._state.phase == 1):
                    self.send(('ACCEPT', 1, 0), to=sender)
            elif (ph == 2):
                if ((self._state.phase == 1) or (self._state.owner == 0)):
                    self.send(('ACCEPT', 2, 0), to=sender)
                    self._state.phase = 2
                else:
                    self.send(('INFORM', self._state.owner), to=sender)
    _P_handler_685._labels = None
    _P_handler_685._notlabels = None

    def _P_handler_853(self, ph, l, sender):
        self.stall()
        self._state.receiving_flag = True
        if ((self._state.waitState == 1) and (ph == 1)):
            self._state.level = ((self._state.level + l) + 1)
            self._state.Received = True
        elif ((self._state.waitState == 2) and (ph == 2)):
            self._state.Response = (self._state.Response + 1)
            if (self._state.Response >= len(self._state.ringPh2)):
                self._state.step = (self._state.step + 1)
                if (self._state.step >= (math.log(self._state.k, 2) + 1)):
                    self._state.state = 'leader'
                else:
                    self._state.Received = True
    _P_handler_853._labels = None
    _P_handler_853._notlabels = None

    def _P_handler_932(self, node, sender):
        self.stall()
        self._state.receiving_flag = True
        if (self._state.waitState == 1):
            self._state.Response = (self._state.Response + 1)
            if (self._state.Response >= (len(self._state.ring) - 1)):
                self._state.phase = 2
    _P_handler_932._labels = None
    _P_handler_932._notlabels = None

    def _P_handler_969(self, node, sender):
        self.stall()
        self._state.receiving_flag = True
        if (self._state.state == 'candidate'):
            self._state.state = 'captured'
            self._state.leaderid = node
        elif (self._state.state == 'captured'):
            self._state.done = True
            self._state.leaderid = node
    _P_handler_969._labels = None
    _P_handler_969._notlabels = None

    def _P_handler_1007(self, x, sender):
        self.stall()
        self._state.receiving_flag = True
        if (self._state.waitState == 2):
            e = self._state.hCycle.index(sender)
            self.send(('CAPTURE', 2, self._state.step, self._id), to=self._state.hCycle[int(((e + x) % self._state.n))])
    _P_handler_1007._labels = None
    _P_handler_1007._notlabels = None

    def _P_handler_1052(self, node, sender):
        self.stall()
        self._state.receiving_flag = True
        if (self._state.waitState == 3):
            self._state.owner = self._state.hCycle.index(node)
            self._state.phase = 2
            self.send(('ACK', node), to=sender)
        elif ((self._state.waitState == 1) and (self._id == node)):
            self._state.owner = self._state.hCycle.index(node)
            self.send(('ACK', node), to=sender)
    _P_handler_1052._labels = None
    _P_handler_1052._notlabels = None

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])
    _config_object = {'channel': 'fifo'}

    def run(self):
        n = (int(sys.argv[1]) if (len(sys.argv) > 1) else 16)
        ps = list(self.new(P, num=n))
        for (i, p) in enumerate(ps):
            self._setup({p}, ([ps[int(((i + j) % n))] for j in range(n)],))
        self.output(time.clock())
        self._start(ps)
